[profile.default]
src = "src"
out = "out"
libs = ["libs", "node_modules"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=node_modules/forge-std/src/",
    "blocklock-solidity/=node_modules/blocklock-solidity/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]
gas_reports = ["*"]

[profile.default.fmt]
sort_imports = true
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
ignore = []

[profile.test]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
